{
  "openapi": "3.0.3",
  "info": {
    "title": "Contact Management RESTful API",
    "description": "OpenAPI for Contact Management RESTful API",
    "version": "1.0.0",
    "contact": {
      "name": "Yeahbutstill A.K.A Dani",
      "email": "mayadani28@gmail.com",
      "url": "https://wwww.github.com/yeahbutstilll"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "Contact Management RESTful API",
      "url": "http://{server.host}:{server.port}/api/v1",
      "variables": {
        "server.host": {
          "description": "The host of the server",
          "default": "localhost",
          "enum": [
            "localhost",
            "yeahbutstill.com"
          ]
        },
        "server.port": {
          "default": "8181",
          "enum": [
            "8181",
            "80",
            "443"
          ]
        }
      }
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Register User",
        "description": "Create new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "yeahbutstill",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "password": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "sangatsangatrahasia",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "name": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "Dani",
                    "maxLength": 100,
                    "minLength": 1
                  }
                }
              },
              "examples": {
                "yeahbutstill": {
                  "value": {
                    "username": "yeahbutstill",
                    "password": "sangatsangatrahasia",
                    "name": "Dani"
                  }
                },
                "maya": {
                  "value": {
                    "username": "mayamayayaya",
                    "password": "sangatsangatrahasia",
                    "name": "Maya"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "OK"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Fail",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Username must not blank, ???"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "User"
        ],
        "summary": "Get Current User",
        "description": "Get current user login",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "username": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "yeahbutstill"
                        },
                        "name": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Dani"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Unauthorized"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "User"
        ],
        "summary": "Update Current User",
        "description": "Update current user but only the name",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "Dani",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "password": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "sangatsangatrahasia",
                    "maxLength": 100,
                    "minLength": 1
                  }
                }
              },
              "examples": {
                "yeahbutstill": {
                  "value": {
                    "name": "Dani",
                    "password": "newpassword"
                  }
                },
                "maya": {
                  "value": {
                    "name": "Maya",
                    "password": "newpassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "username": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "yeahbutstill"
                        },
                        "name": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Dani"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Unauthorized"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Login User",
        "description": "Login user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "yeahbutstill",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "password": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "sangatsangatrahasia",
                    "maxLength": 100,
                    "minLength": 1
                  }
                }
              },
              "examples": {
                "yeahbutstill": {
                  "value": {
                    "username": "yeahbutstill",
                    "password": "sangatsangatrahasia"
                  }
                },
                "maya": {
                  "value": {
                    "username": "mayamayayaya",
                    "password": "sangatsangatrahasia"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "TOKEN"
                        },
                        "expiredAt": {
                          "type": "integer",
                          "nullable": false,
                          "required": true,
                          "default": 234234242342
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Unauthorized"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "delete": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Auth"
        ],
        "summary": "Logout User",
        "description": "Logout user",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "OK"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts": {
      "post": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact"
        ],
        "summary": "Create new contact",
        "description": "Create new contact",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "Maya",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "lastName": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "Sangatsangatrahasia",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "email": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "sangat@gmail",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "phone": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "0987654321",
                    "maxLength": 13,
                    "minLength": 10
                  }
                }
              },
              "examples": {
                "yeahbutstill": {
                  "value": {
                    "firstName": "Dani",
                    "lastName": "Se",
                    "email": "yeahbutstill@gmail",
                    "phone": "0987654321"
                  }
                },
                "maya": {
                  "value": {
                    "firstName": "Maya",
                    "lastName": "Sangatsangatrahasia",
                    "email": "sangat@gmail",
                    "phone": "0987654322"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "random.string.uuid"
                        },
                        "firstName": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Maya",
                          "maxLength": 100,
                          "minLength": 1
                        },
                        "lastName": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Sangatsangatrahasia",
                          "maxLength": 100,
                          "minLength": 1
                        },
                        "email": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "sangat@gmail",
                          "maxLength": 100,
                          "minLength": 1
                        },
                        "phone": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "0987654321",
                          "maxLength": 13,
                          "minLength": 10
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Email format invalid, phone formar invalid, ..."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact"
        ],
        "summary": "Search contacts",
        "description": "Search contacts",
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Contact name",
            "schema": {
              "type": "string",
              "nullable": true,
              "default": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "Maya"
              },
              "dani": {
                "value": "Dani"
              }
            }
          },
          {
            "name": "email",
            "in": "query",
            "required": false,
            "description": "Contact email",
            "schema": {
              "type": "string",
              "nullable": true,
              "default": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "maya@gmail.com"
              },
              "dani": {
                "value": "dani@gmail.com"
              }
            }
          },
          {
            "name": "phone",
            "in": "query",
            "required": false,
            "description": "Contact phone",
            "schema": {
              "type": "string",
              "nullable": true,
              "default": false,
              "maxLength": 13,
              "minLength": 10
            },
            "examples": {
              "maya": {
                "value": "0987654321"
              },
              "dani": {
                "value": "0987654322"
              }
            }
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "description": "Contact page",
            "schema": {
              "type": "integer",
              "nullable": false,
              "default": 0
            }
          },
          {
            "name": "size",
            "in": "query",
            "required": false,
            "description": "Contact size",
            "schema": {
              "type": "integer",
              "nullable": false,
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "name : String, contact first name or last name, using like query, optional\nphone : String, contact phone, using like query, optional\nemail : String, contact email, using like query, optional\npage : Integer, start from 0, default 0\nsize : Integer, default 10",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "random.string.uuid"
                          },
                          "firstName": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "Maya",
                            "maxLength": 100,
                            "minLength": 1
                          },
                          "lastName": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "Sangatsangatrahasia",
                            "maxLength": 100,
                            "minLength": 1
                          },
                          "email": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "sangat@gmail",
                            "maxLength": 100,
                            "minLength": 1
                          },
                          "phone": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "0987654321",
                            "maxLength": 13,
                            "minLength": 10
                          }
                        }
                      }
                    },
                    "paging": {
                      "type": "object",
                      "properties": {
                        "currentPage": {
                          "type": "integer",
                          "nullable": false,
                          "default": 0
                        },
                        "totalPage": {
                          "type": "integer",
                          "nullable": false,
                          "default": 10
                        },
                        "size": {
                          "type": "integer",
                          "nullable": false,
                          "default": 10
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Email format invalid, phone formar invalid, ..."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts/{contactId}": {
      "put": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact"
        ],
        "summary": "Update contact",
        "description": "Update contact",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "MayaNew",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "lastName": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "SangatsangatrahasiaNew",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "email": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "sangat@gmailNew",
                    "maxLength": 100,
                    "minLength": 1
                  },
                  "phone": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "09876543211",
                    "maxLength": 13,
                    "minLength": 10
                  }
                }
              },
              "examples": {
                "maya": {
                  "value": {
                    "firstName": "MayaNew",
                    "lastName": "SangatsangatrahasiaNew",
                    "email": "sangat@gmailNew",
                    "phone": "09876543211"
                  }
                },
                "dani": {
                  "value": {
                    "firstName": "DaniNew",
                    "lastName": "SangatsangatrahasiaNew",
                    "email": "sangat2@gmailNew",
                    "phone": "09876543212"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              },
              "dani": {
                "value": "bdasd-22222-vvvdasd"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "random.string.uuid",
                          "maxLength": 100,
                          "minLength": 1
                        },
                        "firstName": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "MayaNew"
                        },
                        "lastName": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "SangatsangatrahasiaNew"
                        },
                        "email": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "sangat@gmailNew",
                          "maxLength": 100,
                          "minLength": 1
                        },
                        "phone": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "09876543211",
                          "maxLength": 13,
                          "minLength": 10
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Email format invalid, phone formar invalid, ..."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact"
        ],
        "summary": "Delete contact",
        "description": "Delete contact",
        "operationId": "",
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "OK"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Contact not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact"
        ],
        "summary": "Get contact",
        "description": "Get contact",
        "operationId": "",
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "random.string.uuid",
                          "maxLength": 100,
                          "minLength": 1
                        },
                        "firstName": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "MayaNew"
                        },
                        "lastName": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "SangatsangatrahasiaNew"
                        },
                        "email": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "sangat@gmailNew"
                        },
                        "phone": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "09876543211"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Contact not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts/{contactId}/addresses": {
      "post": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact Address"
        ],
        "summary": "Create new contact address",
        "description": "Create new address",
        "operationId": "",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "street": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "JL. nama jalan"
                  },
                  "city": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "Jakarta"
                  },
                  "province": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "DKI Jakarta"
                  },
                  "country": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "Indonesia"
                  },
                  "postalCode": {
                    "type": "string",
                    "nullable": false,
                    "required": true,
                    "default": "12345"
                  }
                }
              },
              "examples": {
                "maya": {
                  "value": {
                    "street": "JL. nama jalan",
                    "city": "Jakarta",
                    "province": "DKI Jakarta",
                    "country": "Indonesia",
                    "postalCode": "12345"
                  }
                },
                "dani": {
                  "value": {
                    "street": "JL. nama jalan",
                    "city": "Jakarta",
                    "province": "DKI Jakarta",
                    "country": "Indonesia",
                    "postalCode": "12345"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "random.string.uuid"
                        },
                        "street": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "JL. nama jalan"
                        },
                        "city": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Jakarta"
                        },
                        "province": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "DKI Jakarta"
                        },
                        "country": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Indonesia"
                        },
                        "postalCode": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "12345"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Contact not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact Address"
        ],
        "summary": "Get all contact addresses",
        "description": "Get all addresses",
        "operationId": "",
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "random.string.uuid"
                          },
                          "street": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "JL. nama jalan"
                          },
                          "city": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "Jakarta"
                          },
                          "province": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "DKI Jakarta"
                          },
                          "country": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "Indonesia"
                          },
                          "postalCode": {
                            "type": "string",
                            "nullable": false,
                            "required": true,
                            "default": "12345"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Contact not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts/{contactId}/addresses/{addressId}": {
      "get": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact Address"
        ],
        "summary": "Get contact address",
        "description": "Get address",
        "operationId": "",
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          },
          {
            "name": "addressId",
            "in": "path",
            "required": true,
            "description": "Address ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "random.string.uuid"
                        },
                        "street": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "JL. nama jalan"
                        },
                        "city": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Jakarta"
                        },
                        "province": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "DKI Jakarta"
                        },
                        "country": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Indonesia"
                        },
                        "postalCode": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "12345"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Contact not found or address not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact Address"
        ],
        "summary": "Delete contact address",
        "description": "Delete address",
        "operationId": "",
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          },
          {
            "name": "addressId",
            "in": "path",
            "required": true,
            "description": "Address ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "OK"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Contact not found or address not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Contact Address"
        ],
        "summary": "Update contact address",
        "description": "Update address",
        "operationId": "",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "street": {
                    "type": "object",
                    "properties": {
                      "street": {
                        "type": "string",
                        "nullable": false,
                        "required": true,
                        "default": "JL. nama jalan"
                      },
                      "city": {
                        "type": "string",
                        "nullable": false,
                        "required": true,
                        "default": "Jakarta"
                      },
                      "province": {
                        "type": "string",
                        "nullable": false,
                        "required": true,
                        "default": "DKI Jakarta"
                      },
                      "country": {
                        "type": "string",
                        "nullable": false,
                        "required": true,
                        "default": "Indonesia"
                      },
                      "postalCode": {
                        "type": "string",
                        "nullable": false,
                        "required": true,
                        "default": "12345"
                      }
                    }
                  }
                }
              },
              "examples": {
                "maya": {
                  "value": {
                    "street": {
                      "street": "JL. nama jalan",
                      "city": "Jakarta",
                      "province": "DKI Jakarta",
                      "country": "Indonesia",
                      "postalCode": "12345"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "description": "Contact ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          },
          {
            "name": "addressId",
            "in": "path",
            "required": true,
            "description": "Address ID",
            "schema": {
              "type": "string",
              "nullable": false,
              "maxLength": 100,
              "minLength": 1
            },
            "examples": {
              "maya": {
                "value": "sdasd-12312-1asdasd"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "random.string.uuid"
                        },
                        "street": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "JL. nama jalan"
                        },
                        "city": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Jakarta"
                        },
                        "province": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "DKI Jakarta"
                        },
                        "country": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "Indonesia"
                        },
                        "postalCode": {
                          "type": "string",
                          "nullable": false,
                          "required": true,
                          "default": "12345"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string",
                      "nullable": false,
                      "required": true,
                      "default": "Contact not found or address not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ContactManagementAuth": {
        "description": "Authentication for Contact Management RESTful API",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    }
  }
}